### ISSUE TITLE
Getting Connector Request Error / Cant use online dashboard

### ISSUE THREAD

**Issue by cbronner35** [balenair/balenair#40]
Hello I'm having an issue with getting the online Grafana dashboard working again. I keep running into balena.exceptions.RequestError: b'Unauthorized' errors. I've included the logs from balena. Its important to note I did have to change the release to the latest focal build because its impossible to build under the bionic build at least for the pi0w2. Currently on the "balenaOS 2.105.21"

[airquality_grumpy-ranch-21.11.22_11_53_54_(-0500).txt](https://github.com/balenair/balenair/files/10058503/airquality_grumpy-ranch-21.11.22_11_53_54_.-0500.txt)

Thanks for any help!

**Comment by mattceh** [comment]
Same here.

**Comment by cbronner35** [comment]
Hey mattceh for some reason my dashboard is working again. Could you check yours to verify and I'll close this issue.
